GET http://localhost:7007/api/events

###

GET http://localhost:7007/api/events/12


###

POST http://localhost:7007/api/events/create

{
"title": "Dans",
"description": "dans",
"date": "2025-02-02",
"time": "10:00",
"duration": 120,
"capacity": 36,
"location": "København",
"instructor": "Bibi",
"price": 125.00,
"status": "Active",
"category": null
}


### virker ikke

PUT http://localhost:7007/api/events/update/

{
"title": "Dans",
"description": "dans",
"date": "2025-02-02",
"time": "10:00",
"duration": 120,
"capacity": 36,
"location": "København",
"instructor": "Bibi",
"price": 125.00,
"status": "Active",
"category": null
}



###virkker ikke

DELETE http://localhost:7007/api/events/delete/7


### users

GET http://localhost:7007/api/users/all

###

GET http://localhost:7007/api/users/70

###

POST http://localhost:7007/api/users/create

{
"name": "Flem",
"password": "66655",
"email": "vvvv@hhhh.com",
"phoneNumber": 55444422

}

### vikker ikke

DELETE http://localhost:7007/api/users/delete/1


### register

GET http://localhost:7007/api/register/all/3


###

GET http://localhost:7007/api/register/1/2


###

POST http://localhost:7007/api/register/create/2/3





### virker ikke

DELETE http://localhost:7007/api/register/delete/1/2

### login
POST http://localhost:7007/api/auth/login
content-type: application/json

{
"name": "qm",
"password": "53655"
}


###
POST http://localhost:7007/api/auth/register
content-type: application/json

{
"name": "qm",
"password": "53655",
"email": "smmmmjjd@",
  "phoneNumber": 12345678
}


###

### get all car Entity

GET http://localhost:7007/api/cars/

### getbyid car Entity

GET http://localhost:7007/api/cars/by/3




### delete car Entity

DELETE http://localhost:7007/api/cars/delete/1


### create car Entity


POST http://localhost:7007/api/cars/create
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "make": "Japan",
  "year": 2020,
  "firstRegistrationDate": 230,
  "price": 18000
}

###update car Entity

PUT http://localhost:7007/api/cars/update/6
Content-Type: application/json

{
  "id": 6,
  "brand": "Toyota",
  "model": "Corolla",
  "make": "Japan",
  "year": 2018,
  "firstRegistrationDate": 2010,
  "price": 18000
}

###


###

