GET http://localhost:7007/api/events

###

GET http://localhost:7007/api/events/1


###

POST http://localhost:7007/api/events/create

{
"title": "Dans",
"description": "dans",
"date": "2025-02-02",
"time": "10:00",
"duration": 120,
"capacity": 36,
"location": "København",
"instructor": "Bibi",
"price": 125.00,
"status": "Active",
"category": null
}


###

PUT http://localhost:7007/api/events/update/6

"title": "Løb",
"description": "løb",
"date": "2027-02-02",
"time": "20:00",
"duration": 90,
"capacity": 40,
"location": "Aarhus",
"instructor": "Bibi",
"price": 75.00,
"status": "Active",
"category": null



###

DELETE http://localhost:7007/api/events/delete/7


###

GET http://localhost:7007/api/users/all

###

GET http://localhost:7007/api/users/1

###

POST http://localhost:7007/api/users/create

{
"name": "Flem",
"password": "66655",
"email": "vvvv@hhhh.com",
"phoneNumber": 55444422

}

###

DELETE http://localhost:7007/api/users/delete/1


###



